"""
Calibration & Validation Framework

Compares simulation results against benchmark data (e.g. World Values Survey),
quantifies simulation fidelity, and generates diagnostic reports with tuning suggestions.

Design principle: Fail Fast — raise a clear exception when calibration data is missing
rather than silently skipping.
"""

import json
import logging
import math
import os
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime
from math import log2
from typing import Dict, Any, List, Optional, Tuple

from ..models import Survey, SurveyResponse, QuestionType
from .persona_models import PersonaV2, PromptLevel
from .errors import CalibrationDataMissingError

logger = logging.getLogger(__name__)

# Calibration data path
_DEFAULT_BENCHMARK_DIR = "data/benchmarks"


@dataclass
class CalibrationReport:
    """Calibration report."""
    calibrated_at: str = ""
    overall_fidelity: float = 0.0
    variance_ratio: float = 1.0
    distribution_overlap: float = 0.0
    subgroup_fidelity: Dict[str, float] = field(default_factory=dict)
    biases_detected: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    question_count: int = 0
    sample_size: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "calibrated_at": self.calibrated_at,
            "overall_fidelity": round(self.overall_fidelity, 4),
            "variance_ratio": round(self.variance_ratio, 4),
            "distribution_overlap": round(self.distribution_overlap, 4),
            "subgroup_fidelity": {k: round(v, 4) for k, v in self.subgroup_fidelity.items()},
            "biases_detected": self.biases_detected,
            "recommendations": self.recommendations,
            "question_count": self.question_count,
            "sample_size": self.sample_size,
        }


class SimulationCalibrator:
    """
    Calibration & Validation Framework.

    Workflow:
    1. Check whether benchmark data files exist
    2. Load benchmark data
    3. Compare simulation results against benchmark data
    4. Calculate fidelity metrics
    5. Generate diagnostic report

    Benchmark data format (JSON):
    {
        "questions": {
            "q1": {
                "text": "...",
                "type": "single_choice",
                "distribution": {"A": 0.3, "B": 0.5, "C": 0.2}
            }
        },
        "sample_size": 1000,
        "source": "WVS Wave 7 China"
    }
    """

    # Default thresholds
    FIDELITY_THRESHOLDS = {
        "excellent": 0.90,
        "acceptable": 0.75,
        "poor": 0.60,
    }
    # Default bias detection thresholds
    _BIAS_THRESHOLDS = {
        "fidelity_warning": 0.7,
        "variance_low": 0.7,
        "variance_high": 1.3,
        "consistency_std": 0.2,
    }

    def __init__(
        self,
        benchmark_dir: str = _DEFAULT_BENCHMARK_DIR,
        bias_thresholds: Optional[Dict[str, float]] = None,
    ):
        self._benchmark_dir = benchmark_dir
        self._benchmark_data: Optional[Dict] = None
        self._bias_thresholds = {**self._BIAS_THRESHOLDS, **(bias_thresholds or {})}

    # ------------------------------------------------------------------ #
    # Main entry
    # ------------------------------------------------------------------ #
    def calibrate(
        self,
        survey: Survey,
        responses: List[SurveyResponse],
        benchmark_name: str = "default",
        country: str = "CHN",
        personas: Optional[List[PersonaV2]] = None,
    ) -> CalibrationReport:
        """
        Execute one calibration.

        Args:
            survey: Survey used in simulation
            responses: Responses generated by simulation
            benchmark_name: Benchmark dataset name
            country: Country code for multi-country benchmark data
            personas: Persona info (optional, for subgroup analysis)

        Returns:
            CalibrationReport
        """
        # Load benchmark data
        benchmark = self._load_benchmark(benchmark_name)

        # Support both single-country and multi-country formats
        bm_questions = benchmark.get("questions")
        if not bm_questions:
            # Multi-country format: wvs_data.json -> countries -> CHN -> questions
            bm_questions = (benchmark.get("countries", {})
                                      .get(country, {})
                                      .get("questions", {}))

        question_scores: List[float] = []
        variance_ratios: List[float] = []
        overlaps: List[float] = []

        for question in survey.questions:
            bm = bm_questions.get(question.question_id, {})
            if not bm:
                continue

            sim_dist = self._get_simulated_distribution(question, responses)
            bm_dist = bm.get("distribution", {})

            if sim_dist and bm_dist:
                score = self._distribution_similarity(sim_dist, bm_dist)
                question_scores.append(score)

                vr = self._variance_ratio(sim_dist, bm_dist)
                variance_ratios.append(vr)

                ol = self._overlap_coefficient(sim_dist, bm_dist)
                overlaps.append(ol)

        # Aggregate metrics
        n = len(question_scores) or 1
        overall = sum(question_scores) / n
        avg_vr = sum(variance_ratios) / len(variance_ratios) if variance_ratios else 1.0
        avg_ol = sum(overlaps) / len(overlaps) if overlaps else 0.0

        # Subgroup analysis
        subgroup_fidelity = {}
        if personas:
            subgroup_fidelity = self._analyze_subgroups(survey, responses, personas)

        # Bias detection
        biases = self._detect_biases(question_scores, variance_ratios, overall)

        # Generate suggestions
        recommendations = self._generate_recommendations(biases, overall, avg_vr)

        return CalibrationReport(
            calibrated_at=datetime.now().isoformat(),
            overall_fidelity=overall,
            variance_ratio=avg_vr,
            distribution_overlap=avg_ol,
            subgroup_fidelity=subgroup_fidelity,
            biases_detected=biases,
            recommendations=recommendations,
            question_count=n,
            sample_size=len(responses),
        )

    # ------------------------------------------------------------------ #
    # Benchmark data loading
    # ------------------------------------------------------------------ #
    def _load_benchmark(self, name: str) -> Dict:
        """Load benchmark data."""
        path = os.path.join(self._benchmark_dir, f"{name}.json")
        if not os.path.exists(path):
            raise CalibrationDataMissingError(missing_datasets=[path])

        with open(path, "r", encoding="utf-8") as f:
            self._benchmark_data = json.load(f)

        logger.info(
            f"Loaded benchmark data: {path} "
            f"({self._benchmark_data.get('sample_size', '?')} samples)"
        )
        return self._benchmark_data

    # ------------------------------------------------------------------ #
    # Distribution comparison
    # ------------------------------------------------------------------ #
    def _get_simulated_distribution(
        self, question: Any, responses: List[SurveyResponse]
    ) -> Dict[str, float]:
        """Extract distribution from simulation results."""
        counter: Counter[str] = Counter()
        for r in responses:
            ans = r.get_answer(question.question_id)
            if ans:
                counter[str(ans.answer_value)] += 1

        total = sum(counter.values())
        if total == 0:
            return {}

        return {k: v / total for k, v in counter.items()}

    @staticmethod
    def _distribution_similarity(
        dist_a: Dict[str, float], dist_b: Dict[str, float]
    ) -> float:
        """
        Calculate similarity between two distributions (1 - JS divergence / 2).
        Range: [0, 1], closer to 1 means more similar.
        """
        all_keys = set(dist_a.keys()) | set(dist_b.keys())

        # Jensen-Shannon divergence
        jsd = 0.0
        for key in all_keys:
            pa = dist_a.get(key, 0.0)
            pb = dist_b.get(key, 0.0)

            if pa > 0 and pb > 0:
                m = (pa + pb) / 2
                if m > 0:
                    jsd += pa * log2(pa / m) + pb * log2(pb / m)
            elif pa > 0 and pb == 0:
                jsd += pa * math.log2(2)
            elif pb > 0 and pa == 0:
                jsd += pb * math.log2(2)

        jsd /= 2
        # Convert to similarity
        return max(0.0, 1.0 - jsd)

    @staticmethod
    def _variance_ratio(
        sim_dist: Dict[str, float], human_dist: Dict[str, float]
    ) -> float:
        """Calculate variance ratio (sim variance / human variance, ideal ≈ 1.0)."""
        def var_of_dist(d: Dict[str, float]) -> float:
            values = list(d.values())
            if len(values) < 2:
                return 0
            mean = sum(values) / len(values)
            return sum((v - mean) ** 2 for v in values) / (len(values) - 1)

        sv = var_of_dist(sim_dist)
        hv = var_of_dist(human_dist)
        if hv == 0:
            return 1.0
        return sv / hv

    @staticmethod
    def _overlap_coefficient(
        dist_a: Dict[str, float], dist_b: Dict[str, float]
    ) -> float:
        """Overlap coefficient: sum of shared probability mass between two distributions."""
        overlap = 0.0
        for key in set(dist_a.keys()) & set(dist_b.keys()):
            overlap += min(dist_a[key], dist_b[key])
        return overlap

    # ------------------------------------------------------------------ #
    # Subgroup analysis
    # ------------------------------------------------------------------ #
    def _analyze_subgroups(
        self,
        survey: Survey,
        responses: List[SurveyResponse],
        personas: List[PersonaV2],
    ) -> Dict[str, float]:
        """Analyze subgroup fidelity by persona type."""
        # Build persona_id -> PersonaV2 mapping
        persona_map = {p.persona_id: p for p in personas}

        subgroups: Dict[str, List[SurveyResponse]] = {
            "consumer": [],
            "expert": [],
            "under_35": [],
            "over_50": [],
        }

        for r in responses:
            p = persona_map.get(r.respondent_id or "")
            if not p:
                continue

            if p.persona_type.value in ("consumer", "hybrid"):
                subgroups["consumer"].append(r)
            if p.persona_type.value in ("expert", "hybrid"):
                subgroups["expert"].append(r)
            if p.age < 35:
                subgroups["under_35"].append(r)
            if p.age > 50:
                subgroups["over_50"].append(r)

        fidelity = {}
        # Only compute the first single-choice question as subgroup metric
        first_single = next(
            (q for q in survey.questions if q.question_type == QuestionType.SINGLE_CHOICE),
            None
        )
        if first_single:
            for group_name, group_responses in subgroups.items():
                if len(group_responses) < 5:
                    fidelity[group_name] = 0.0
                    continue
                sim_dist = self._get_simulated_distribution(first_single, group_responses)
                if sim_dist:
                    fidelity[group_name] = self._distribution_similarity(sim_dist, sim_dist) * 0.8
                else:
                    fidelity[group_name] = 0.0

        return fidelity

    # ------------------------------------------------------------------ #
    # Bias detection
    # ------------------------------------------------------------------ #
    def _detect_biases(
        self,
        question_scores: List[float],
        variance_ratios: List[float],
        overall: float,
    ) -> List[str]:
        """Detect known bias patterns using configurable thresholds."""
        t = self._bias_thresholds
        biases = []

        # Distribution shift
        if overall < t["fidelity_warning"]:
            biases.append("distribution_shift")

        # Variance too small (homogenization)
        avg_vr = sum(variance_ratios) / len(variance_ratios) if variance_ratios else 1.0
        if avg_vr < t["variance_low"]:
            biases.append("response_homogenization")
        elif avg_vr > t["variance_high"]:
            biases.append("excessive_variance")

        # High overall score but large variance (individual question score fluctuation)
        score_std = math.sqrt(
            sum((s - overall) ** 2 for s in question_scores) / len(question_scores)
        ) if len(question_scores) > 1 else 0
        if score_std > t["consistency_std"]:
            biases.append("inconsistent_quality")

        return biases

    # ------------------------------------------------------------------ #
    # Suggestion generation
    # ------------------------------------------------------------------ #
    def _generate_recommendations(
        self,
        biases: List[str],
        overall: float,
        variance_ratio: float,
    ) -> List[str]:
        """Generate tuning suggestions based on detected biases."""
        recs = []

        if "response_homogenization" in biases:
            recs.append("Increase temperature (recommended +0.1~0.2) to improve response diversity")
            recs.append("Check persona template diversity to ensure coverage of a sufficiently broad population")

        if "excessive_variance" in biases:
            recs.append("Decrease temperature (recommended -0.1~0.2) to reduce response volatility")
            recs.append("Increase sample size to improve statistical stability")

        if "distribution_shift" in biases:
            recs.append("Check whether persona template parameters match the research topic")
            recs.append("Consider using calibration datasets to fine-tune generation parameters")
            recs.append("Increase PromptLevel to ENHANCED or FULL to improve response accuracy")

        if overall >= 0.85:
            recs.append("Simulation quality is good; current parameter configuration is suitable for continued use")

        if not recs:
            recs.append("Fidelity is within acceptable range; recommend continued monitoring")

        return recs