# -*- coding: utf-8 -*-
"""
TaskStructureAnalyzer - Task Structure Analyzer (Dynamic Analysis Version)

Analyzes task internal structure, dynamically identifies section roles and content dependencies.

Core design concepts:
1. No hardcoded section types, instead dynamically analyze each section's "role"
2. Use LLM to analyze dependencies between sections
3. Dynamically generate execution plan based on analysis results

Section roles (SectionRole):
- DATA_COLLECTION: Data collection type (collect raw data)
- ANALYSIS: Analysis type (analyze data)
- SYNTHESIS: Synthesis type (needs other sections to complete before generating)
- SUPPORTING: Supporting type (appendix, data sources, etc.)

Design document: .sisyphus/plans/intelligent_routing_system_design.md
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple
import logging
import re
import json
import asyncio

logger = logging.getLogger(__name__)

# Import existing types
from .semantic_intent import DeepIntentResult
from .research_type import ResearchType
from .prompt_manager import PromptManager


class SectionRole(Enum):
    """
    Section role (dynamic analysis result)

    Not predefined types, but roles dynamically determined based on section content.

    Role definitions:
    - DATA_COLLECTION: Data collection type - collects raw data, no dependency on other sections
    - ANALYSIS: Analysis type - analyzes data, may depend on data collection sections
    - SYNTHESIS: Synthesis type - needs other sections to complete before generating (e.g. summary, conclusion)
    - SUPPORTING: Supporting type - appendix, data sources and other supporting content
    """
    DATA_COLLECTION = "data_collection"
    ANALYSIS = "analysis"
    SYNTHESIS = "synthesis"
    SUPPORTING = "supporting"


@dataclass
class SectionSpec:
    """
    Section Specification

    Describes a section's role, dependencies and execution characteristics.
    Dynamically generated by LLM analysis, not using predefined templates.
    """
    section_id: str                         # Unique identifier
    section_name: str                       # Section name
    section_role: SectionRole               # Section role (dynamic analysis result)
    role_reasoning: str = ""                # Role reasoning (LLM output)
    content_dependency: List[str] = field(default_factory=list)  # Dependent section IDs
    dependency_reasoning: str = ""          # Dependency reasoning
    skill_requirements: List[str] = field(default_factory=list)  # Required Skills
    estimated_complexity: str = "medium"    # "low" / "medium" / "high"
    can_parallel: bool = True               # Whether can parallelize with other sections
    priority: int = 0                       # Execution priority
    config: Dict[str, Any] = field(default_factory=dict)  # Extensible section-level metadata

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary"""
        return {
            "section_id": self.section_id,
            "section_name": self.section_name,
            "section_role": self.section_role.value,
            "role_reasoning": self.role_reasoning,
            "content_dependency": self.content_dependency,
            "dependency_reasoning": self.dependency_reasoning,
            "skill_requirements": self.skill_requirements,
            "estimated_complexity": self.estimated_complexity,
            "can_parallel": self.can_parallel,
            "priority": self.priority,
            "config": self.config,
        }


@dataclass
class ContentDependency:
    """
    Content Dependency

    Describes content dependencies between sections, dynamically generated by LLM analysis.
    """
    from_section: str                       # Source section ID
    to_section: str                         # Target section ID
    dependency_type: str                    # "data" / "analysis" / "synthesis"
    dependency_reason: str = ""             # Dependency reason (LLM output)
    unlock_condition: str = "completion"    # "completion" / "quality_threshold" / "both"
    quality_threshold: float = 0.75

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary"""
        return {
            "from_section": self.from_section,
            "to_section": self.to_section,
            "dependency_type": self.dependency_type,
            "dependency_reason": self.dependency_reason,
            "unlock_condition": self.unlock_condition,
            "quality_threshold": self.quality_threshold,
        }


@dataclass
class TaskStructure:
    """
    Task Structure

    Complete description of a task's internal structure and execution characteristics.
    """
    task_id: str
    topic: str
    sections: List[SectionSpec] = field(default_factory=list)
    dependencies: List[ContentDependency] = field(default_factory=list)
    execution_graph: Dict[str, List[str]] = field(default_factory=dict)
    parallel_groups: List[List[str]] = field(default_factory=list)
    critical_path: List[str] = field(default_factory=list)
    total_estimated_agents: int = 0
    analysis_method: str = "rule_based"     # "rule_based" / "llm_based"

    def get_section_by_id(self, section_id: str) -> Optional[SectionSpec]:
        """Get section by ID"""
        for section in self.sections:
            if section.section_id == section_id:
                return section
        return None

    def get_sections_by_role(self, role: SectionRole) -> List[SectionSpec]:
        """Get sections by role"""
        return [s for s in self.sections if s.section_role == role]

    def get_data_collection_sections(self) -> List[SectionSpec]:
        """Get all data collection sections"""
        return self.get_sections_by_role(SectionRole.DATA_COLLECTION)

    def get_analysis_sections(self) -> List[SectionSpec]:
        """Get all analysis sections"""
        return self.get_sections_by_role(SectionRole.ANALYSIS)

    def get_synthesis_sections(self) -> List[SectionSpec]:
        """Get all synthesis sections"""
        return self.get_sections_by_role(SectionRole.SYNTHESIS)
    
    def get_data_dependencies(self, section_name: str) -> List[str]:
        """R-FIX-2: infer upstream section IDs this section depends on for data.
        Uses keyword mapping; returns matching section IDs.
        """
        _DATA_DEP_MAP = {
            "财务": ["营收", "利润", "盈利", "收入", "成本"],
            "盈利": ["营收", "利润", "收入", "成本", "毛利率"],
            "销量": ["财务", "营收", "利润", "出口", "海外"],
            "市场": ["财务", "销量", "竞争", "份额"],
            "竞争": ["财务", "市场", "盈利"],
            "研发": ["财务", "盈利", "收入"],
            "风险": ["财务", "竞争", "政策", "海外"],
            "国际化": ["财务", "销量", "盈利"],
            "预测": ["财务", "盈利", "研发", "国际化", "竞争"],
            "季度": ["财务", "盈利", "销量"],
        }
        name_lower = section_name.lower()
        upstream, seen = [], set()
        for kw, deps in _DATA_DEP_MAP.items():
            if kw in name_lower:
                for dep in deps:
                    for s in self.sections:
                        if dep in s.section_name.lower() and s.section_id not in seen:
                            seen.add(s.section_id)
                            upstream.append(s.section_id)
        return upstream
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary"""
        return {
            "task_id": self.task_id,
            "topic": self.topic,
            "sections": [s.to_dict() for s in self.sections],
            "dependencies": [d.to_dict() for d in self.dependencies],
            "execution_graph": self.execution_graph,
            "parallel_groups": self.parallel_groups,
            "critical_path": self.critical_path,
            "total_estimated_agents": self.total_estimated_agents,
            "analysis_method": self.analysis_method,
        }


# Section analysis prompt moved to prompts/agents/section_analysis_system.md / section_analysis_user.md
# Load via PromptManager


class TaskStructureAnalyzer:
    """
    Task Structure Analyzer (Dynamic Analysis Version)

    Core concepts:
    1. No hardcoded section types
    2. Dynamically analyze each section's role
    3. Dynamically identify dependencies between sections
    4. Generate execution plan based on analysis results

    Usage example:
        analyzer = TaskStructureAnalyzer(use_llm=True)
        structure = analyzer.analyze(
            intent=deep_intent,
            aspects=["Market Size", "Competitive Landscape", "Technology Trends", "Executive Summary"]
        )
    """

    # Synthesis section keywords (for rule engine quick judgment)
    SYNTHESIS_KEYWORDS = [
        # Summary type
        "摘要", "执行摘要", "核心摘要", "summary", "executive summary",
        "核心洞察", "关键发现", "key insights", "key findings",
        # Conclusion type
        "结论", "研究结论", "总结", "研究总结", "conclusion", "findings",
        # Synthesis type
        "综合分析", "综合研判", "整体分析", "综合评估",
        # Forecast / outlook type (added P2)
        "趋势预测", "价格展望", "后市判断", "后市分析",
        "前景预测", "走势分析", "趋势研判",
        "forecast", "outlook", "projection",
    ]

    # Supporting section keywords
    SUPPORTING_KEYWORDS = [
        "附录", "appendix", "数据来源", "data source",
        "参考文献", "references", "研究方法", "methodology",
    ]

    # Data collection section keywords
    DATA_COLLECTION_KEYWORDS = [
        "数据收集", "数据采集", "信息收集", "data collection",
        "调研", "survey", "问卷", "访谈", "interview",
    ]

    def __init__(
        self,
        use_llm: bool = True,
        fallback_to_rule: bool = True,
        llm_model: Optional[str] = None,
    ):
        """
        Initialize task structure analyzer

        Args:
            use_llm: Whether to use LLM for dynamic analysis
            fallback_to_rule: Whether to fallback to rule engine when LLM fails
            llm_model: Specify LLM model
        """
        self._use_llm = use_llm
        self._fallback_to_rule = fallback_to_rule
        self._llm_model = llm_model

        logger.info(f"TaskStructureAnalyzer initialized: use_llm={use_llm}, fallback={fallback_to_rule}")

    def analyze(
        self,
        intent: DeepIntentResult,
        aspects: List[str],
        task_id: Optional[str] = None,
        topic: Optional[str] = None,
    ) -> TaskStructure:
        """
        Analyze task structure

        Args:
            intent: Deep intent analysis result
            aspects: Section list
            task_id: Task ID
            topic: Report topic

        Returns:
            TaskStructure: Task structure
        """
        import uuid
        task_id = task_id or f"task_{uuid.uuid4().hex[:8]}"

        # Ensure topic has value (type safety)
        if topic is None:
            topic = intent.domain_context.get("industry", "") or "Research Topic"

        # At this point topic type is confirmed as str
        assert topic is not None

        logger.info(f"[{task_id}] Analyzing task structure: {len(aspects)} sections")

        # Try LLM analysis
        if self._use_llm:
            try:
                # P1-2: Detect whether we're inside a running event loop.
                # asyncio.run() raises RuntimeError when called from within
                # an async context (e.g. an orchestrator running on an asyncio server).
                try:
                    loop = asyncio.get_running_loop()
                except RuntimeError:
                    loop = None

                if loop is not None:
                    # We are inside an async context — schedule the coroutine
                    # on the existing loop rather than creating a new one.
                    future = asyncio.ensure_future(
                        self._analyze_with_llm(intent, aspects, task_id, topic),
                        loop=loop,
                    )
                    # Run until complete in a thread-safe manner.
                    # Note: this blocks the caller but does NOT attempt to
                    # create a new event loop.
                    if not loop.is_running():
                        return loop.run_until_complete(future)
                    else:
                        # Loop is running (we're inside an async handler).
                        # Use run_coroutine_threadsafe on a dedicated thread
                        # as a fallback to avoid deadlock.
                        import concurrent.futures
                        with concurrent.futures.ThreadPoolExecutor() as pool:
                            return pool.submit(
                                asyncio.run,
                                self._analyze_with_llm(intent, aspects, task_id, topic),
                            ).result(timeout=120)
                else:
                    return asyncio.run(self._analyze_with_llm(
                        intent, aspects, task_id, topic
                    ))
            except Exception as e:
                logger.warning(f"LLM structure analysis failed: {e}")
                if self._fallback_to_rule:
                    logger.info("Falling back to rule-based analysis")
                    return self._analyze_with_rules(intent, aspects, task_id, topic)
                raise

        # Use rule engine
        return self._analyze_with_rules(intent, aspects, task_id, topic)

    async def _analyze_with_llm(
        self,
        intent: DeepIntentResult,
        aspects: List[str],
        task_id: str,
        topic: str,
    ) -> TaskStructure:
        """Use LLM for dynamic structure analysis"""

        # Load section analysis prompt from PromptManager
        pm = PromptManager.get_instance()
        try:
            system_prompt = pm.render("agents", "section_analysis_system")
            user_template = pm.render("agents", "section_analysis_user")
        except FileNotFoundError:
            logger.warning("Section analysis prompt files not found, using fallback")
            system_prompt = "You are a professional report structure analysis expert. Please analyze the role and dependencies of report sections."
            user_template = "Please analyze the following report's section structure:\n\nReport topic: {topic}\nSection list: {sections}\n\nPlease output each section's role analysis and dependencies (JSON format)."

        # Escape curly braces in topic to prevent str.format injection
        safe_topic = topic.replace("{", "{{").replace("}", "}}")
        prompt = user_template.format(
            topic=safe_topic,
            sections=json.dumps(aspects, ensure_ascii=False),
        )

        # Call LLM
        from src.core.llm_client import call_llm
        from src.config.llm_profiles import RoutingHint

        result = await call_llm(
            prompt=prompt,
            system_prompt=system_prompt,
            model=self._llm_model or None,
            max_tokens=2048,
            temperature=0.1,
            routing_hint=RoutingHint(action="task_structure"),
        )
        
        if not result.get("success"):
            raise ValueError(f"LLM call failed: {result.get('error')}")

        content = result.get("content", "")

        # Parse JSON
        llm_output = self._parse_llm_json(content)

        # Build TaskStructure
        return self._build_structure_from_llm(
            llm_output, aspects, task_id, topic, intent
        )

    def _parse_llm_json(self, content: str) -> Dict[str, Any]:
        """Parse LLM output JSON"""
        content = content.strip()
        
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
        
        content = content.strip()
        
        try:
            result = json.loads(content)
        except json.JSONDecodeError as e:
            logger.warning(f"Failed to parse LLM JSON: {e}")
            logger.debug(f"Raw LLM output: {content[:500]}")
            return {"sections": [], "reasoning": "LLM returned invalid JSON"}
        
        # Guard: LLM may return a JSON array instead of an object
        if isinstance(result, list):
            logger.warning(
                f"LLM returned a JSON array ({len(result)} items) instead of an object. "
                f"Wrapping in {{\"sections\": ...}}"
            )
            return {"sections": result}
        if not isinstance(result, dict):
            logger.warning(
                f"LLM returned unexpected type {type(result).__name__}, "
                f"returning empty dict as fallback"
            )
            return {}
        return result
    
    def _build_structure_from_llm(
        self,
        llm_output: Dict[str, Any],
        aspects: List[str],
        task_id: str,
        topic: str,
        intent: DeepIntentResult,
    ) -> TaskStructure:
        """Build TaskStructure from LLM output"""
        sections = []
        section_id_map = {}  # name -> id

        # Parse section analysis results
        section_analyses = llm_output.get("sections", [])

        for i, aspect in enumerate(aspects):
            section_id = f"section_{i}_{self._sanitize_id(aspect)}"
            section_id_map[aspect] = section_id

            # Find LLM analysis for this section
            analysis = None
            for sa in section_analyses:
                if sa.get("name") == aspect or sa.get("section_name") == aspect:
                    analysis = sa
                    break

            if analysis:
                # Use LLM analysis result
                role_str = analysis.get("role", "analysis").upper()
                try:
                    role = SectionRole[role_str]
                except KeyError:
                    role = SectionRole.ANALYSIS

                section = SectionSpec(
                    section_id=section_id,
                    section_name=aspect,
                    section_role=role,
                    role_reasoning=analysis.get("role_reasoning", ""),
                    skill_requirements=analysis.get("skills", []),
                    can_parallel=analysis.get("can_parallel", True),
                    estimated_complexity=analysis.get("complexity", "medium"),
                )
            else:
                # Fallback to rule judgment
                role = self._classify_section_role(aspect)
                section = SectionSpec(
                    section_id=section_id,
                    section_name=aspect,
                    section_role=role,
                    role_reasoning="Rule-based fallback",
                    can_parallel=role != SectionRole.SYNTHESIS,
                )

            sections.append(section)

        # Parse dependencies
        dependencies = []
        dep_analyses = llm_output.get("dependencies", [])

        for dep in dep_analyses:
            from_name = dep.get("from")
            to_name = dep.get("to")

            from_id = section_id_map.get(from_name)
            to_id = section_id_map.get(to_name)

            if from_id and to_id:
                dependencies.append(ContentDependency(
                    from_section=from_id,
                    to_section=to_id,
                    dependency_type=dep.get("type", "synthesis"),
                    dependency_reason=dep.get("reason", ""),
                ))

                # Update section's dependency list
                for s in sections:
                    if s.section_id == to_id:
                        s.content_dependency.append(from_id)

        # If LLM didn't output dependencies, use rule inference
        if not dependencies:
            dependencies = self._infer_dependencies(sections, intent)

        # Build execution graph
        execution_graph = self._build_execution_graph(sections, dependencies)
        parallel_groups = self._compute_parallel_groups(sections, dependencies)
        critical_path = self._compute_critical_path(sections, dependencies)
        total_agents = self._estimate_total_agents(sections, intent)

        return TaskStructure(
            task_id=task_id,
            topic=topic,
            sections=sections,
            dependencies=dependencies,
            execution_graph=execution_graph,
            parallel_groups=parallel_groups,
            critical_path=critical_path,
            total_estimated_agents=total_agents,
            analysis_method="llm_based",
        )

    def _analyze_with_rules(
        self,
        intent: DeepIntentResult,
        aspects: List[str],
        task_id: str,
        topic: str,
    ) -> TaskStructure:
        """Use rule engine for structure analysis (fallback)"""
        sections = []

        for i, aspect in enumerate(aspects):
            section_id = f"section_{i}_{self._sanitize_id(aspect)}"
            role = self._classify_section_role(aspect)

            section = SectionSpec(
                section_id=section_id,
                section_name=aspect,
                section_role=role,
                role_reasoning=f"Matched keywords for {role.value}",
                skill_requirements=self._infer_skills(aspect, role, intent),
                can_parallel=role != SectionRole.SYNTHESIS,
                estimated_complexity=self._estimate_complexity(aspect, intent),
            )
            sections.append(section)

        # Infer dependencies
        dependencies = self._infer_dependencies(sections, intent)

        # Build execution graph
        execution_graph = self._build_execution_graph(sections, dependencies)
        parallel_groups = self._compute_parallel_groups(sections, dependencies)
        critical_path = self._compute_critical_path(sections, dependencies)
        total_agents = self._estimate_total_agents(sections, intent)

        return TaskStructure(
            task_id=task_id,
            topic=topic,
            sections=sections,
            dependencies=dependencies,
            execution_graph=execution_graph,
            parallel_groups=parallel_groups,
            critical_path=critical_path,
            total_estimated_agents=total_agents,
            analysis_method="rule_based",
        )

    def _classify_section_role(self, aspect: str) -> SectionRole:
        """Use rules to determine section role"""
        aspect_lower = aspect.lower()

        # Check synthesis type
        # Short keywords (≤2 chars) use exact match to prevent false positives
        # e.g. "结论" should not match "数据结构"
        for kw in self.SYNTHESIS_KEYWORDS:
            kw_lower = kw.lower()
            if len(kw) <= 2:
                if kw_lower == aspect_lower:
                    return SectionRole.SYNTHESIS
            else:
                if kw_lower in aspect_lower:
                    return SectionRole.SYNTHESIS

        # Check supporting type
        for kw in self.SUPPORTING_KEYWORDS:
            kw_lower = kw.lower()
            if len(kw) <= 2:
                if kw_lower == aspect_lower:
                    return SectionRole.SUPPORTING
            else:
                if kw_lower in aspect_lower:
                    return SectionRole.SUPPORTING

        # Check data collection type
        for kw in self.DATA_COLLECTION_KEYWORDS:
            kw_lower = kw.lower()
            if len(kw) <= 2:
                if kw_lower == aspect_lower:
                    return SectionRole.DATA_COLLECTION
            else:
                if kw_lower in aspect_lower:
                    return SectionRole.DATA_COLLECTION

        # Default to analysis type
        return SectionRole.ANALYSIS

    def _infer_dependencies(
        self,
        sections: List[SectionSpec],
        intent: DeepIntentResult,
    ) -> List[ContentDependency]:
        """
        Infer dependencies between sections

        Rules:
        1. SYNTHESIS role sections depend on all ANALYSIS sections
        2. ANALYSIS sections may depend on DATA_COLLECTION sections
        """
        dependencies = []

        analysis_sections = [s for s in sections if s.section_role == SectionRole.ANALYSIS]
        synthesis_sections = [s for s in sections if s.section_role == SectionRole.SYNTHESIS]
        data_sections = [s for s in sections if s.section_role == SectionRole.DATA_COLLECTION]

        # Synthesis depends on all analysis
        for synthesis in synthesis_sections:
            for analysis in analysis_sections:
                dependencies.append(ContentDependency(
                    from_section=analysis.section_id,
                    to_section=synthesis.section_id,
                    dependency_type="synthesis",
                    dependency_reason="Synthesis section needs analysis sections to complete",
                ))
                synthesis.content_dependency.append(analysis.section_id)

            # Also depends on data collection
            for data in data_sections:
                dependencies.append(ContentDependency(
                    from_section=data.section_id,
                    to_section=synthesis.section_id,
                    dependency_type="synthesis",
                    dependency_reason="Synthesis section needs data collection sections to complete",
                ))
                synthesis.content_dependency.append(data.section_id)

        # Analysis depends on data collection (if exists)
        for analysis in analysis_sections:
            for data in data_sections:
                dependencies.append(ContentDependency(
                    from_section=data.section_id,
                    to_section=analysis.section_id,
                    dependency_type="data",
                    dependency_reason="Analysis section needs output from data collection sections",
                ))
                analysis.content_dependency.append(data.section_id)

        return dependencies

    def _infer_skills(
        self,
        aspect: str,
        role: SectionRole,
        intent: DeepIntentResult,
    ) -> List[str]:
        """
        Infer skills needed for section

        P0-3 fix: Enhanced inference logic, supports more research dimensions
        """
        skills = set()

        if role == SectionRole.DATA_COLLECTION:
            skills.add("search_skill")

        if role == SectionRole.ANALYSIS:
            skills.add("search_skill")
            aspect_lower = aspect.lower()

            # P0-3 fix: Extended keyword matching, supports more dimensions
            # Financial/valuation related
            if any(kw in aspect_lower for kw in ["财务", "估值", "financial", "营收", "利润", "市值"]):
                skills.add("stock_analysis")
                skills.add("data_analysis")

            # Data/statistics related
            if any(kw in aspect_lower for kw in ["数据", "data", "统计", "指标"]):
                skills.add("data_analysis")
                skills.add("lc_python_repl")

            # Market size/share related
            if any(kw in aspect_lower for kw in ["市场规模", "市场份额", "market size", "market share", "规模", "份额"]):
                skills.add("data_analysis")
                skills.add("lc_python_repl")

            # Competitive landscape related
            if any(kw in aspect_lower for kw in ["竞争", "竞争格局", "competit", "对手", "企业分析"]):
                skills.add("market_analysis")
                skills.add("data_analysis")

            # Industry trend related
            if any(kw in aspect_lower for kw in ["趋势", "行业趋势", "trend", "发展", "前景", "预测"]):
                skills.add("data_analysis")

            # Industry chain related
            if any(kw in aspect_lower for kw in ["产业链", "价值链", "chain", "供应链", "上下游"]):
                skills.add("market_analysis")

            # Policy/regulation related
            if any(kw in aspect_lower for kw in ["政策", "法规", "policy", "监管", "合规"]):
                skills.add("search_skill")

            # Technology related
            if any(kw in aspect_lower for kw in ["技术", "technology", "创新", "研发"]):
                skills.add("lc_arxiv")

        if intent.recommended_skills:
            skills.update(intent.recommended_skills)

        return list(skills)

    def _estimate_complexity(self, aspect: str, intent: DeepIntentResult) -> str:
        """Estimate section complexity"""
        if intent.complexity.value in ("trivial", "single"):
            return "low"
        elif intent.complexity.value == "complex":
            return "high"
        return "medium"

    def _build_execution_graph(
        self,
        sections: List[SectionSpec],
        dependencies: List[ContentDependency],
    ) -> Dict[str, List[str]]:
        """Build execution graph (DAG adjacency list)"""
        graph: Dict[str, List[str]] = {s.section_id: [] for s in sections}

        for dep in dependencies:
            if dep.from_section not in graph:
                graph[dep.from_section] = []
            graph[dep.from_section].append(dep.to_section)

        return graph

    def _compute_parallel_groups(
        self,
        sections: List[SectionSpec],
        dependencies: List[ContentDependency],
    ) -> List[List[str]]:
        """Compute parallelizable section groups (topological sort layers)"""
        in_degree: Dict[str, int] = {s.section_id: 0 for s in sections}

        for dep in dependencies:
            in_degree[dep.to_section] = in_degree.get(dep.to_section, 0) + 1

        reverse_graph: Dict[str, List[str]] = {s.section_id: [] for s in sections}
        for dep in dependencies:
            reverse_graph[dep.to_section].append(dep.from_section)

        groups: List[List[str]] = []
        remaining = set(in_degree.keys())

        # Add cycle detection protection
        max_iterations = len(sections) + 1
        iterations = 0

        while remaining:
            iterations += 1
            if iterations > max_iterations:
                logger.error("Cycle detected in dependency graph")
                groups.append(list(remaining))
                break

            current_group = [node for node in remaining if in_degree[node] == 0]

            if not current_group:
                # Cycle detected in dependencies
                logger.warning(f"Cycle detected in dependencies, forcing remaining nodes: {remaining}")
                groups.append(list(remaining))
                break

            groups.append(current_group)

            for node in current_group:
                remaining.remove(node)
                for dependent in reverse_graph.get(node, []):
                    if dependent in in_degree:
                        in_degree[dependent] -= 1

        return groups

    def _compute_critical_path(
        self,
        sections: List[SectionSpec],
        dependencies: List[ContentDependency],
    ) -> List[str]:
        """Compute critical path (longest dependency chain)"""
        graph: Dict[str, List[str]] = {s.section_id: [] for s in sections}
        in_degree: Dict[str, int] = {s.section_id: 0 for s in sections}

        for dep in dependencies:
            graph[dep.from_section].append(dep.to_section)
            in_degree[dep.to_section] = in_degree.get(dep.to_section, 0) + 1

        path_length: Dict[str, int] = {s.section_id: 1 for s in sections}
        predecessor: Dict[str, Optional[str]] = {s.section_id: None for s in sections}

        queue = [s.section_id for s in sections if in_degree[s.section_id] == 0]
        sorted_nodes = []

        while queue:
            node = queue.pop(0)
            sorted_nodes.append(node)

            for neighbor in graph.get(node, []):
                in_degree[neighbor] -= 1
                if in_degree[neighbor] == 0:
                    queue.append(neighbor)

        for node in sorted_nodes:
            for neighbor in graph.get(node, []):
                if path_length[neighbor] < path_length[node] + 1:
                    path_length[neighbor] = path_length[node] + 1
                    predecessor[neighbor] = node

        end_node = max(path_length.keys(), key=lambda k: path_length[k])

        path = []
        current = end_node
        while current:
            path.append(current)
            current = predecessor.get(current)

        return list(reversed(path))

    def _estimate_total_agents(
        self,
        sections: List[SectionSpec],
        intent: DeepIntentResult,
    ) -> int:
        """Estimate total agent count"""
        count = len(sections)

        if intent.requires_primary_data:
            count += 2  # Survey related agents

        return count + 1  # +1 for report generation

    def _sanitize_id(self, name: str) -> str:
        """Convert name to valid ID"""
        sanitized = re.sub(r'[^\w\u4e00-\u9fff]', '_', name)
        return sanitized[:30].strip('_')


__all__ = [
    "TaskStructureAnalyzer",
    "TaskStructure",
    "SectionSpec",
    "SectionRole",
    "ContentDependency",
]
