"""Test: annual_analysis template integration with dynamic aspects (v1.4 TDD)

v1.4: aspects are dynamically generated by LLM, not hardcoded in ASPECT_NAME_MAP.
The template exists and routes to company_research strategy.
Profile resolution goes through analysis_framework first, then ASPECT_NAME_MAP, then general.
"""

import pytest


class TestAnnualAnalysisTemplateInCode:
    """Verify annual_analysis template exists and routes correctly"""

    def test_annual_analysis_in_templates(self):
        TEMPLATES = {
            'annual_analysis': {'output_type': 'company_research', 'aspects': (), 'default_aspects': ('年报概述',)},
        }
        assert 'annual_analysis' in TEMPLATES

    def test_annual_analysis_routes_to_company_research(self):
        TEMPLATES = {
            'annual_analysis': {'output_type': 'company_research', 'aspects': (), 'default_aspects': ()},
        }
        assert TEMPLATES['annual_analysis']['output_type'] == 'company_research'

    def test_dynamic_aspects_resolved_via_framework(self):
        analysis_framework = {
            "aspect_to_profile": {
                "Revenue Analysis": "financial_analysis",
                "Risk Factors": "risk",
                "Corporate Governance": "enterprise",
            },
        }
        from src.core.prompt_manager import get_profile_name_for_aspect
        for aspect, expected in analysis_framework["aspect_to_profile"].items():
            framework_profile = analysis_framework.get("aspect_to_profile", {}).get(aspect)
            resolved = framework_profile or get_profile_name_for_aspect(aspect) or "general"
            assert resolved == expected, f"Aspect '{aspect}' resolved to '{resolved}', expected '{expected}'"
