"""Test: annual_analysis template uses dynamic aspects (v1.4 TDD)

v1.4: TEMPLATES["annual_analysis"]["aspects"] is empty (dynamically generated by LLM).
default_aspects provides Chinese fallback for A-share only.
"""

import pytest


class TestAnnualAnalysisTemplateDynamic:
    """annual_analysis template aspects are dynamically generated"""

    def test_aspects_empty_for_dynamic_generation(self):
        TEMPLATES = {
            'annual_analysis': {
                'output_type': 'company_research',
                'aspects': (),
                'default_aspects': ('年报概述', '经营分析', '深度财务分析', '现金流分析', '治理与内控', '战略规划', '展望', '投资评估', '风险因素'),
            },
        }
        assert TEMPLATES['annual_analysis']['aspects'] == ()

    def test_default_aspects_provided_as_fallback(self):
        TEMPLATES = {
            'annual_analysis': {
                'output_type': 'company_research',
                'aspects': (),
                'default_aspects': ('年报概述', '经营分析', '深度财务分析', '现金流分析', '治理与内控', '战略规划', '展望', '投资评估', '风险因素'),
            },
        }
        assert len(TEMPLATES['annual_analysis']['default_aspects']) == 9

    def test_output_type_is_company_research(self):
        TEMPLATES = {
            'annual_analysis': {'output_type': 'company_research', 'aspects': (), 'default_aspects': ()},
        }
        assert TEMPLATES['annual_analysis']['output_type'] == 'company_research'

    def test_aspects_falls_back_to_default_aspects(self):
        TEMPLATES = {
            'annual_analysis': {
                'output_type': 'company_research',
                'aspects': (),
                'default_aspects': ('年报概述', '经营分析', '深度财务分析'),
            },
        }
        template = TEMPLATES['annual_analysis']
        aspects = template['aspects'] or template.get('default_aspects', ())
        assert aspects == ('年报概述', '经营分析', '深度财务分析')

    def test_explicit_aspects_not_overridden(self):
        TEMPLATES = {
            'industry_research': {
                'output_type': 'industry_report',
                'aspects': ('市场定义', '市场规模'),
                'default_aspects': (),
            },
        }
        template = TEMPLATES['industry_research']
        aspects = template['aspects'] or template.get('default_aspects', ())
        assert aspects == ('市场定义', '市场规模')
